	DB	"< = > @ < = > @ < = > @ ",0
	DB	"CMP = DRILL = AST        ",0
	DB	"SID < KRIS ? DEMONIAK   ",0
	DB	"THE WHOLE IMPACT TEAM  ",0
	DB	"WOULD LIKE TO WISH YOU  ",0
	DB	"#   A MERRY XMAS 2021   # ",0
	DB	"& HAPPY NEW YEAR 2022 ",0
	DB	"WE HOPE 2022 WILL BE    ",0
	DB	"FULL OF NEW PRODS !!!    ",0
	DB	"& WITHOUT NEW VIRUSES   ",0
	DB	"GREETINGS 2 ALL CPC FAN ",0
	DB	"THIS DEMO HAS BEEN    ",0
	DB	"CODED IN 2 WEEKS BY     ",0
	DB	"D E M O N I A K     =    ",0 
	DB	"GFX & FONT BY : K R I S  ? ",0
	DB	"IDEAS SUPPORT : C M P  =  ",0
	DB	"SPECIAL DEDICATION TO :  ",0
	DB 	"ARKOS = BATMAN GROUP  ",0
	DB	"BND > CONDENSE       ",0
	DB	"DIRTY MINDS EASTER EGG  ",0
	DB	"FUTURS > GGP < GPA      ",0
	DB	"LOGON SYSTEM = NPS     ",0
	DB	"OVERLANDERS @ PRALINE ",0
	DB	"PULPO CORROSIVO  ?     ",0
	DB	"RESISTANCE = REVIVAL    ",0
	DB	"SHINRA @ SML = SYMBIOSIS",0
	DB	"TGS > VANITY          ",0

